services:
  postgres:
    image: postgres:15
    container_name: face_register_postgres_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}_dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - person_detection
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: face_register_minio_dev
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_dev_data:/data
    networks:
      - person_detection
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  app:
    image: face-register:dev
    build:
      dockerfile: Dockerfile
      target: development
    container_name: face_register_app_dev
    environment:
      DATABASE_URL: ${DATABASE_URL}_dev
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SECURE: ${MINIO_SECURE}
      SCRFD_BUCKET: ${SCRFD_BUCKET}
      SCRFD_MODEL_OBJECT: ${SCRFD_MODEL_OBJECT}
      ARCFACE_BUCKET: ${ARCFACE_BUCKET}
      ARCFACE_MODEL_OBJECT: ${ARCFACE_MODEL_OBJECT}
      API_PREFIX: ${API_PREFIX}
      PROJECT_NAME: ${PROJECT_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
      ADMIN_PANEL_URL: ${ADMIN_PANEL_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./assets:/app/assets
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - person_detection
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_dev_data:
  minio_dev_data:

networks:
  person_detection:
    external: true
