services:
  postgres:
    image: postgres:15
    container_name: face_register_postgres_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}_prod
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-UTC}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - person_detection
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: face_register_minio_prod
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      TZ: ${TZ:-UTC}
    command: server /data
    volumes:
      - minio_prod_data:/data
    networks:
      - person_detection
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: face_register_qdrant_prod
    environment:
      TZ: ${TZ:-UTC}
    # ports:
    #   - "6333:6333"
    #   - "6334:6334"
    volumes:
      - qdrant_prod_data:/qdrant/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - person_detection
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  db_migrate:
    image: face-register:prod
    build:
      dockerfile: Dockerfile
      target: production
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
        LOG_DIR: ${LOG_DIR}
    container_name: face_register_db_migrate_prod
    user: "${APP_UID}:${APP_GID}"
    environment:
      DATABASE_URL: ${DATABASE_URL}_prod
      SERVICE_NAME: ${SERVICE_NAME}
      LOG_DIR: ${LOG_DIR}
      LOG_TO_STDOUT: ${LOG_TO_STDOUT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_MAX_DAYS: ${LOG_MAX_DAYS}
      TZ: ${TZ:-UTC}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - person_detection
    restart: "no"
    command: ["alembic", "-c", "app/alembic.ini", "upgrade", "head"]

  app_prod:
    image: face-register:prod
    build:
      dockerfile: Dockerfile
      target: production
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
        LOG_DIR: ${LOG_DIR}
    container_name: face_register_app_prod
    user: "${APP_UID}:${APP_GID}"
    environment:
      DATABASE_URL: ${DATABASE_URL}_prod
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SECURE: ${MINIO_SECURE}
      SCRFD_BUCKET: ${SCRFD_BUCKET}
      SCRFD_MODEL_OBJECT: ${SCRFD_MODEL_OBJECT}
      ARCFACE_BUCKET: ${ARCFACE_BUCKET}
      ARCFACE_MODEL_OBJECT: ${ARCFACE_MODEL_OBJECT}
      API_PREFIX: ${API_PREFIX}
      PROJECT_NAME: ${PROJECT_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
      ADMIN_PANEL_URL: ${ADMIN_PANEL_URL}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION}
      QDRANT_VECTOR_SIZE: ${QDRANT_VECTOR_SIZE}
      SERVICE_NAME: ${SERVICE_NAME}
      LOG_DIR: ${LOG_DIR}
      LOG_TO_STDOUT: ${LOG_TO_STDOUT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_MAX_DAYS: ${LOG_MAX_DAYS}
      TZ: ${TZ:-UTC}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - person_detection
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]

volumes:
  postgres_prod_data:
  minio_prod_data:
  qdrant_prod_data:

networks:
  person_detection:
    external: true
