services:
  postgres:
    image: postgres:15
    container_name: face_register_postgres_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}_dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-UTC}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    networks:
      - person_detection
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: face_register_minio_dev
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      TZ: ${TZ:-UTC}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_dev_data:/data
    networks:
      - person_detection
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: face_register_qdrant_dev
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_dev_data:/qdrant/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - person_detection
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  db_migrate:
    image: face-register:dev
    build:
      dockerfile: Dockerfile
      target: development
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
        LOG_DIR: ${LOG_DIR}
    container_name: face_register_db_migrate_dev
    environment:
      DATABASE_URL: ${DATABASE_URL}_dev
      SERVICE_NAME: ${SERVICE_NAME}
      LOG_DIR: ${LOG_DIR}
      LOG_TO_STDOUT: ${LOG_TO_STDOUT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_MAX_DAYS: ${LOG_MAX_DAYS}
      TZ: ${TZ:-UTC}
    volumes:
      - ./app:/app/app
      - ./assets:/app/assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - person_detection
    restart: "no"
    command: ["alembic", "-c", "app/alembic.ini", "upgrade", "head"]

  app:
    image: face-register:dev
    build:
      dockerfile: Dockerfile
      target: development
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
        LOG_DIR: ${LOG_DIR}
    container_name: face_register_app_dev
    environment:
      DATABASE_URL: ${DATABASE_URL}_dev
      MODEL_RUNTIME_TYPE: ${MODEL_RUNTIME_TYPE}
      TRITON_SERVER_URL: ${TRITON_SERVER_URL}
      API_TOKEN: ${API_TOKEN}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SECURE: ${MINIO_SECURE}
      SCRFD_BUCKET: ${SCRFD_BUCKET}
      SCRFD_MODEL_OBJECT: ${SCRFD_MODEL_OBJECT}
      ARCFACE_BUCKET: ${ARCFACE_BUCKET}
      ARCFACE_MODEL_OBJECT: ${ARCFACE_MODEL_OBJECT}
      API_PREFIX: ${API_PREFIX}
      PROJECT_NAME: ${PROJECT_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
      ADMIN_PANEL_URL: ${ADMIN_PANEL_URL}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION}
      QDRANT_VECTOR_SIZE: ${QDRANT_VECTOR_SIZE}
      SERVICE_NAME: ${SERVICE_NAME}
      LOG_DIR: ${LOG_DIR}
      LOG_TO_STDOUT: ${LOG_TO_STDOUT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_MAX_DAYS: ${LOG_MAX_DAYS}
      TZ: ${TZ:-UTC}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./assets:/app/assets
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - person_detection
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_dev_data:
  minio_dev_data:
  qdrant_dev_data:

networks:
  person_detection:
    external: true
