"""add face_embeddings table

Revision ID: 7c341e510476
Revises: 10e24f287c7a
Create Date: 2025-08-31 15:58:05.598079

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c341e510476"
down_revision: Union[str, Sequence[str], None] = "10e24f287c7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "face_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_face_embeddings_id"), "face_embeddings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_face_embeddings_user_id"), "face_embeddings", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_face_embeddings_user_id"), table_name="face_embeddings")
    op.drop_index(op.f("ix_face_embeddings_id"), table_name="face_embeddings")
    op.drop_table("face_embeddings")
    # ### end Alembic commands ###
