"""Save image into blob storage

Revision ID: 9b70bcd0c868
Revises: 7c341e510476
Create Date: 2025-09-07 15:41:44.121423

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b70bcd0c868"
down_revision: Union[str, Sequence[str], None] = "7c341e510476"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "face_embeddings", sa.Column("image_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("face_embeddings", "image_path")
    # ### end Alembic commands ###
